### ISSUE TITLE
checkorder.xhtml

### ISSUE THREAD

**Issue by cn222hn** [IHotWoan/TheBestProjectGroup#7] opened 2016-05-18 08:41 UTC
When I enter in a email to see my order number it is all okai the first time but the more times i repeat this step the more of the same order number i see. So basically the order number increases in quantity even though I have made no new orders!
![error2](https://cloud.githubusercontent.com/assets/18505988/15352559/0e9db3e8-1ce5-11e6-9292-c5a9cb4d5179.png)

**Comment by songhokun** [comment] 2016-05-18 08:43
Thank you for reporting. The issue is being fixed now!

**Closed as completed** 2016-05-18 20:00 UTC
